### PR TITLE
Connect db with create recipe page

### PR DESCRIPTION
**Pull request by lik5**
Still need to do edge case testing, validation checking and write test

Can create new recipe from this page now

Screenshot 2024-02-22 at 10 16 49 PM

### CODE REVIEW

**Comment by Rloeppky** [comment]
Currently I can not tell if the db is interacting fully correctly as I can not add any ingredients or instructions. However the page does recognize that they are needed to create a recipe.

image
image

**Comment by lik5** [comment]
> Currently I can not tell if the db is interacting fully correctly as I can not add any ingredients or instructions. However the page does recognize that they are needed to create a recipe.
> 
> image image

So the way it works, is it requires the instruction/ingredient to be non-empty and you need at least one or more of each. Did you mean that you couldn't type in the input fields?

**Comment by Rloeppky** [comment]
Yes, when entering an ingredient it is typing in the instruction box with only one letter and when I type in the instruction box it types one letter and then deselects the object. No ingredients can be added and instructions are only at max two characters.

**Comment by lik5** [comment]
> Yes, when entering an ingredient it is typing in the instruction box with only one letter and when I type in the instruction box it types one letter and then deselects the object. No ingredients can be added and instructions are only at max two characters.

Fixed!

**Review by hwbit — APPROVED** [review]

**Pull request merged**
