### PR TITLE
ESLint config

### PR DESCRIPTION
**Pull request by algorizan**
Added and changed some ESLint settings to better fit our project.

### CODE REVIEW

**Comment by algorizan** [comment]
Can someone please check that eslint isn't giving you any errors on the "name" property at the top of our package.json files? I'm having some trouble with a wrong error being triggered there but idk if it's just my VS Code or what

**Review by lik5 — APPROVED** [review]
I don't know anything about eslint scripts but hopefully this works :D

**Comment by lik5** [comment]
Don't see any weird errors in my package.json files

**Review by Rloeppky — APPROVED** [review]
Like Kenny, I don't know much about eslint, but running your branch hasn't caused issues with 'npm start' or 'npm run build', so I approve.

**Pull request merged**
